---

# @author Bodo (Hugo) Barwich
# @version 2021-09-04
# @package Plack Twiggy REST API
# @subpackage /config/default.yml

# This is the Default Service Configuration
# This will be loaded when no customized Configuration exists
#

project: 'Plack Twiggy PWA'
codename: 'PlackPWA'
version: '0.0.1'
vmainpath: '/'
maindirectory: ''
